repos:
# Some generally used hooks for sanity-check
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending

# Applies formating and linting to CMake files
-   repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
    -   id: cmake-format
        additional_dependencies: [pyyaml]
        types: [file]
        files: (\.cmake|CMakeLists.txt)(.in)?$
    -   id: cmake-lint
        types: [file]
        files: (\.cmake|CMakeLists.txt)(.in)?$

# Changes tabs to spaces
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.7
    hooks:
    -   id: remove-tabs
